aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-cust-cluster-adm: "true"
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that has restrigted admins rights within the clutser and can
      create a project with specific node-selector
  labels:
    kubernetes.io/bootstrapping: rbac-custom-rule
  name: cust-cluster-adm
