aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-cust-security-officer: "true"
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that has securite officer rights within a cluster
  labels:
    kubernetes.io/bootstrapping: rbac-custom-rule
  name: cust-security-officer